// Generated by CoffeeScript 1.6.3
(function() {
  var EventEmitter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require('events').EventEmitter;

  module.exports.Base = (function(_super) {
    __extends(Base, _super);

    function Base(options) {
      this.options = options != null ? options : {};
      this.log = this.debug = require('debug')("xbmc-remote-keyboard:" + this.constructor.name);
      this.debug('constructor');
      return this;
    }

    return Base;

  })(EventEmitter);

}).call(this);
