// Generated by CoffeeScript 1.4.0
(function() {
  var Base, Ui, ncurses,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require('./Base').Base;

  ncurses = require('ncurses');

  Ui = (function(_super) {

    __extends(Ui, _super);

    function Ui() {
      this.input = __bind(this.input, this);

      this.start = __bind(this.start, this);
      return Ui.__super__.constructor.apply(this, arguments);
    }

    Ui.prototype.start = function() {
      var _this = this;
      this.log('start');
      return setTimeout((function() {
        return _this.input(42);
      }), 1000);
    };

    Ui.prototype.input = function(input) {
      this.log('input', input);
      return this.emit('input', input);
    };

    return Ui;

  })(Base);

  module.exports = {
    Ui: Ui
  };

}).call(this);
